name: SkyBlockMultiplayer
main: me.lukas.skyblockmultiplayer.SkyBlockMultiplayer
version: 0.45 alpha

commands:
     skyblock:
          description: Use /skyblock [arguments] to get access to the plugin. 
          usage: /<command>

author: Seadragon91
authors: [Ktesibios]
website: https://github.com/Leseratte91/SkyBlock-Multiplayer
