name: SkyblockMultiplayer
main: me.lukas.skyblockmultiplayer.SkyblockMultiplayer
version: 0.42 alpha

commands:
     skyblock:
          description: Use /skyblock [arguments] to get access to the plugin. 
          usage: /<command>
