name: SkyBlockMultiplayer
main: me.lukas.skyblockmultiplayer.SkyBlockMultiplayer
version: 0.55

commands:
  skyblock:
    description: Use /skyblock [arguments] to get access to the plugin.
    aliases: [sb]
    usage: /<command>

author: Seadragon91
authors: [Ktesibios]
website: https://github.com/Leseratte91/SkyBlock-Multiplayer
